name: run test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.47.0
      with:
        ruby-version: 2.7.1
    
    - run: |
        ruby -v
        ls -la
        ls -la app/