name: run test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.47.0
      with:
        ruby-version: 2.7.1
    
    - name: Cache vendor/bundle
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Bundle install
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install
        
    - run: mysql --version
    - run: cat db/schema.rb

    - name: Set up MySQL
      run: |
        cp config/database_ci.yml config/database.yml
        bin/rails db:create 
        bin/rails db:schema:load
      env:
        RAILS_ENV: test

    - run: gem list
    - run: which rspec
    - run: bundle exec rspec
