name: run test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.47.0
      with:
        ruby-version: 2.7.1
    
    - run: ruby -v

    - name: Set up Bundler
      run: |
        gem install bundler
        bundle install
        
    - run: mysql --version
    - run: cat db/schema.rb

    - name: Set up MySQL
      run: |
        cp config/database_ci.yml config/database.yml
        bin/rails db:create
        bin/rails db:schema:load

    - run: gem list
    - run: which rspec
    - run: bundle exec rspec
